# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
  # valid drivers options include "gd" or "gmagick" or "imagick"
  driver: "gd"
  resolvers:
    default:
      web_path: ~
  filter_sets:
    cache: ~

    # the name of the "filter set"
    thumbnail_comment:
      quality: 75
      filters:
        thumbnail: { size: [ 75, 75 ], mode: outbound }
    avatar:
      quality: 75
      filters:
        thumbnail: { size: [ 200, 200 ], mode: outbound }
    trick_slides:
      quality: 75
      filters:
        thumbnail: { size: [ 182, 135 ], mode: outbound }

