@startuml
scale 800 width
skinparam classBackgroundColor #f1ffe7
skinparam classBorderColor #1a1b41
Class Trick {
-id: integer
-name: string
-description: text
-tricks_group: integer
-medias
}
Class TricksGroup {
  -id: integer
  -name: string
  -description: text
}
Class Media {
  -id: integer
  -name: string
  -description: text
  -file: string
  -type: string
}
Class User {
  -id: integer
  -name: string
  -email: string
  -password:string
  -connected: boolean
  -avatar: id
}
Class Comment {
  -id: integer
  -content: text
  -date: datetime
  -trick
  -user
}
Class TokenHistory {
  -id: integer
  -createdAt: datetime
  -value: string
  -type: string
  -user: User
}


Media "0..1" --o  "1" User
Trick  "0..*" *--  "1..*" User
Trick "0..*" -- "1" TricksGroup
User  "1" *--  "0..*" Comment
Media  "0..*" --o "1" Trick
Comment "0..*" --* "0..*" Trick
User "1" --* "0..*" TokenHistory



@enduml