@startuml
scale 800 width
skinparam classBackgroundColor #f1ffe7
skinparam classBorderColor #1a1b41
Class Trick {
-id: integer
-name: string
-description: text
-tricks_group: integer
-medias
}
Class TricksGroup {
  -id: integer
  -name: string
  -description: text
}
Class Media {
  -id: integer
  -name: string
  -description: text
  -file: string
  -type: string
}
Class User {
  -id: integer
  -name: string
  -email: string
  -password:string
  -connected: boolean
  -avatar: id
}
Class Comment {
  -id: integer
  -content: text
  -date: datetime
  -trick
  -user
}
Class TokenHistory {
  -id: integer
  -createdAt: datetime
  -value: string
  -type: string
  -user: User
}


Media "one" --o  "one" User
Trick  "one" *--  "many" User
Trick "many" -- "one" TricksGroup
User  "one" *--  "many" Comment
Media  "one" -o "many" Trick
Comment "one" --* "one" Trick
User "one" --* "many" TokenHistory



@enduml